log.level: ${LOG_LEVEL:WARN}

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: g21
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100

      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        isolation.level: read_committed
        max.poll.interval.ms: 600000

    producer:
      transaction-id-prefix: transactionx-
      acks: all
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 180000

logging.level:
  ROOT: DEBUG
  org.springframework:
    kafka: TRACE
    boot.autoconfigure: WARN

request.topic: req-tpc
response.topic: resp-tpc